name: "Install Titanium SDK"
description: "Install Titanium SDK"

inputs:
  version:
    description: "The Titanium SDK version you want to install. e.g. 11.1.1.GA"
    required: false
    default: "11.1.1.GA"

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3

  - uses: actions/setup-java@v3
    with:
      distribution: 'adopt'
      java-version: '11'

  - name: Node install
    uses: actions/setup-node@v3
    with:
      node-version: 16

  - name: Cache Gradle packages
    uses: actions/cache@v3
    with:
      path: |
        ~/.gradle/caches
        ~/.gradle/wrapper
      key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      restore-keys: |
        ${{ runner.os }}-gradle-

  - name: Cache Node.js modules
    id: node-cache
    uses: actions/cache@v3
    with:
      path: node_modules
      key: ${{ runner.OS }}-node-modules-${{ hashFiles('package-lock.json') }}
      restore-keys: |
        ${{ runner.OS }}-node-modules-
        ${{ runner.OS }}-

  - name: Install Titanium
    run: |
      sudo npm i -g titanium appcelerator alloy

      ti sdk install ${{ inputs.version }}
      ti sdk select ${{ inputs.version }}
      sudo chmod 777 /Users/runner/Library/'Application Support'/Titanium/modules/android
      sudo chmod 777 /Users/runner/Library/'Application Support'/Titanium/modules/iphone
      sudo chmod 777 /Users/runner/.titanium

branding:
  icon: "smartphone"
  color: "red"
